##############################
# Netlify configuration file #
##############################

# List of Build plugins

[build]
# Dummy build command
command = "echo onBuild"
publish = "/"

[build.environment]
NODE_VERSION = "16.9.0"